image: salesforce/salesforcedx:7.129.0-full

clone:
  depth: full

pipelines:
  # See https://www.lucidchart.com/invitations/accept/7d58d35d-ddbe-409e-8e7b-a1bf280069d7 for trouble shooting
  pull-requests:
    "**":
      - step:
          name: "Build Package"
          script:
            - if git log -1 | grep -q "\\[skip ci\\]"; then printf 'CI Commit... Skipping pipeline!'; exit; fi
            - if [ "${BITBUCKET_PR_DESTINATION_BRANCH}" != "master" ]; then printf 'Destination is not master... Skipping pipeline'; exit; fi
            - ./build/setup.sh
            - pr_description=$(curl -s https://${BITBUCKET_USERNAME}:${BITBUCKET_APP_PASSWORD}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/pullrequests/${BITBUCKET_PR_ID} | jq -r '.description')
            - SKIP_SYNC=$(echo "$pr_description" | grep -i -c \!skipsync) || true
            - echo Skip Sync $SKIP_SYNC
            - ./build/sync.sh $SKIP_SYNC
            - ./build/package.sh
          artifacts:
            - dist/**
      - step:
          name: Check Package
          trigger: manual
          script:
            - ./build/setup.sh
            - pr_description=$(curl -s https://${BITBUCKET_USERNAME}:${BITBUCKET_APP_PASSWORD}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/pullrequests/${BITBUCKET_PR_ID} | jq -r '.description')
            - TESTS=$(echo "$pr_description" | grep -i \!tests= | cut -d "=" -f 2-) || true
            - echo Tests $TESTS
            - DEPLOY_ID=$(sfdx force:mdapi:deploy ${TESTS:+ -l RunSpecifiedTests -r "${TESTS}"} -d dist/$BITBUCKET_BRANCH -c --json | jq -r .result.id)
            - echo $DEPLOY_ID
            - echo $DEPLOY_ID > dist/deploy_id.txt
            - sfdx force:mdapi:deploy:report --jobid $DEPLOY_ID -w 1000
          artifacts:
            - dist/**
      - step:
          name: Quick Deploy
          trigger: manual
          script:
            - ./build/setup.sh
            - DEPLOY_ID=$(cat dist/deploy_id.txt)
            - echo $DEPLOY_ID
            - sfdx force:mdapi:deploy -q $DEPLOY_ID -w 1000
            - ./build/merge.sh
  custom:
    Sync Production:
      - step:
          script:
            - ./build/setup.sh
            - ./build/sync.sh
    Deploy to Production:
      - variables:
          - name: Enter1ToSkipProdSync
      - step:
          script:
            - ./build/setup.sh
            - ./build/sync.sh $Enter1ToSkipProdSync
            - ./build/package.sh
            - sfdx force:mdapi:deploy -d dist/$BITBUCKET_BRANCH -w 5000 --verbose
            - ./build/merge.sh
    Deploy to Production (Selective Tests):
      - variables:
          - name: Enter1ToSkipProdSync
          - name: Tests
      - step:
          script:
            - ./build/setup.sh
            - ./build/sync.sh $Enter1ToSkipProdSync
            - ./build/package.sh
            - sfdx force:mdapi:deploy -d dist/$BITBUCKET_BRANCH -w 5000 -l RunSpecifiedTests -r $Tests --verbose
            - ./build/merge.sh
    Scheduled Production Sync:
      - step:
          script:
            - ./build/schedule.sh
